// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Coordinating_Batteries_Entities_DatNT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace Coordinating_Batteries_Repositories_DatNT.Models;

public partial class PRN212_SE1906_SE190283Context : DbContext
{
    public PRN212_SE1906_SE190283Context()
    {

    }

    public PRN212_SE1906_SE190283Context(DbContextOptions<PRN212_SE1906_SE190283Context> options)
        : base(options)
    {
    }

    public virtual DbSet<BatteryTransferDatNt> BatteryTransferDatNts { get; set; }

    public virtual DbSet<StationDatNt> StationDatNts { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-MDFL445G;Initial Catalog=PRN212_SE1906_SE190283;Persist Security Info=True;User ID=SA;Password=12345;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BatteryTransferDatNt>(entity =>
        {
            entity.ToTable("BatteryTransferDatNT");

            entity.HasIndex(e => e.FromStationDatNtid, "IX_BatteryTransferDatNT_FromStation");

            entity.HasIndex(e => e.ToStationDatNtid, "IX_BatteryTransferDatNT_ToStation");

            entity.Property(e => e.BatteryTransferDatNtid).HasColumnName("BatteryTransferDatNTId");
            entity.Property(e => e.BatteryCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CompletedDate).HasColumnType("datetime");
            entity.Property(e => e.FromStationDatNtid).HasColumnName("FromStationDatNTId");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.Quantity).HasDefaultValue(1);
            entity.Property(e => e.RequestDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SoHpercent)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("SoHPercent");
            entity.Property(e => e.ToStationDatNtid).HasColumnName("ToStationDatNTId");
            entity.Property(e => e.TransportCost).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.FromStationDatNt).WithMany(p => p.BatteryTransferDatNtFromStationDatNts)
                .HasForeignKey(d => d.FromStationDatNtid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BatteryTransferDatNT_FromStation");

            entity.HasOne(d => d.ToStationDatNt).WithMany(p => p.BatteryTransferDatNtToStationDatNts)
                .HasForeignKey(d => d.ToStationDatNtid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BatteryTransferDatNT_ToStation");
        });

        modelBuilder.Entity<StationDatNt>(entity =>
        {
            entity.ToTable("StationDatNT");

            entity.Property(e => e.StationDatNtid).HasColumnName("StationDatNTId");
            entity.Property(e => e.Address).HasMaxLength(500);
            entity.Property(e => e.PublishDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.StationName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Status).HasDefaultValue(1);
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}