// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coordinating_Batteries_Entities_DatNT.Models;

public partial class BatteryTransferDatNt
{
    public int BatteryTransferDatNtid { get; set; }

    public string BatteryCode { get; set; }

    public int FromStationDatNtid { get; set; }

    public int ToStationDatNtid { get; set; }

    public int Quantity { get; set; }

    public decimal? SoHpercent { get; set; }

    public decimal? TransportCost { get; set; }

    public DateTime RequestDate { get; set; }

    public DateTime? CompletedDate { get; set; }

    public int Status { get; set; }

    public string Note { get; set; }

    public bool IsActive { get; set; }

    public virtual StationDatNt FromStationDatNt { get; set; }

    public virtual StationDatNt ToStationDatNt { get; set; }
}