// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Coordinating_Batteries_Entities_DatNT.Models;

public partial class StationDatNt
{
    public int StationDatNtid { get; set; }

    public string StationName { get; set; }

    public string Address { get; set; }

    public int? Capacity { get; set; }

    public int Status { get; set; }

    public DateTime? PublishDate { get; set; }

    public virtual ICollection<BatteryTransferDatNt> BatteryTransferDatNtFromStationDatNts { get; set; } = new List<BatteryTransferDatNt>();

    public virtual ICollection<BatteryTransferDatNt> BatteryTransferDatNtToStationDatNts { get; set; } = new List<BatteryTransferDatNt>();
}